# Generated by Django 4.2.5 on 2023-09-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='count',
            new_name='quantity',
        ),
    ]
